const products = [
    {
        id: 1,
        name: "Aliquam Blandit",
        category: "Tables",
        price: 320,
        oldPrice: null,
        image: require("../../assets/product (1).webp"),
    },
    {
        id: 2,
        name: "Augue Lacus",
        category: "Beds",
        price: 800,
        oldPrice: null,
        image: require("../../assets/product (2).webp"),
    },
    {
        id: 3,
        name: "Augue Mauris",
        category: "Chairs",
        price: 85,
        oldPrice: null,
        image: require("../../assets/product(3).webp"),
    },
    {
        id: 4,
        name: "Bibendum Arcu",
        category: "Chairs",
        price: 40,
        oldPrice: 65,
        image: require("../../assets/product (4).webp"),
    },
    {
        id: 5,
        name: "Commodo Amorper",
        category: "Beds",
        price: 1250,
        oldPrice: null,
        image: require("../../assets/product (5).webp"),
    },
    {
        id: 6,
        name: "Diam Arcu",
        category: "Sofas",
        price: 380,
        oldPrice: 450,
        image: require("../../assets/product(6).webp"),
    },
    {
        id: 7,
        name: "Diam Volutpat",
        category: "Decor",
        price: 250,
        oldPrice: null,
        image: require("../../assets/product (7).webp"),
    },
    {
        id: 8,
        name: "Dolore Magna",
        category: "Beds",
        price: 1000,
        oldPrice: null,
        image: require("../../assets/product(8).webp"),
    },
];

export default products;
