const productss = [
    {
        id: 1,
        name: "Massa Scelerisque",
        category: "Tables",
        price: 790.00,
        oldPrice: null,
        image: require("./assets/product-32-300x300.webp"),
    },
    {
        id: 2,
        name: "Sem Integer",
        category: "Storage",
        price: 800,
        oldPrice: null,
        image: require("./assets/product-30-300x300.webp"),
    },
    {
        id: 3,
        name: "Lectus Proin",
        category: "Tables",
        price: 85,
        oldPrice: null,
        image: require("./assets/product-31-300x300.webp"),
    },
    {
        id: 4,
        name: "Mollis Nunc",
        category: "Storage",
        price: 40,
        oldPrice: 65,
        image: require("./assets/product-29-300x300.webp"),
    },

    {
        id: 1,
        name: "Aliquam Blandit",
        category: "Tables",
        price: 320,
        oldPrice: null,
        image: require("./assets/product (1).webp"),
    },
    {
        id: 2,
        name: "Augue Lacus",
        category: "Beds",
        price: 800,
        oldPrice: null,
        image: require("./assets/product (2).webp"),
    },
    {
        id: 3,
        name: "Augue Mauris",
        category: "Chairs",
        price: 85,
        oldPrice: null,
        image: require("./assets/product(3).webp"),
    },
    {
        id: 4,
        name: "Bibendum Arcu",
        category: "Chairs",
        price: 40,
        oldPrice: 65,
        image: require("./assets/product (4).webp"),
    },
    {
        id: 5,
        name: "Commodo Amorper",
        category: "Beds",
        price: 1250,
        oldPrice: null,
        image: require("./assets/product (5).webp"),
    },
    {
        id: 6,
        name: "Diam Arcu",
        category: "Sofas",
        price: 380,
        oldPrice: 450,
        image: require("./assets/product(6).webp"),
    },
    {
        id: 7,
        name: "Diam Volutpat",
        category: "Decor",
        price: 250,
        oldPrice: null,
        image: require("./assets/product (7).webp"),
    },
    {
        id: 8,
        name: "Dolore Magna",
        category: "Beds",
        price: 1000,
        oldPrice: null,
        image: require("./assets/product(8).webp"),
    },
  ];
  
  export default productss;